import { LenormandCard } from "../types";

export const LENORMAND_CARDS: LenormandCard[] = [
  {
    id: "rider-dark",
    archetype: "rider",
    aspect: "dark",
    name: "騎士",
    title: "暗影騎士",
    basic: "消息、靠近、推進",
    tags: ["試探", "惡意接近", "突發消息", "急躁", "外來能量"],
    aiFocus: ["從困境解救", "誰正在靠近", "動機與目的"],
    image: "/lenormand/dark/rider.png",
  },

  {
    id: "clover-dark",
    archetype: "clover",
    aspect: "dark",
    name: "幸運草",
    title: "暗影幸運草",
    basic: "機運、短暫機會、偶然",
    tags: ["短暫", "機會", "僥倖", "不穩定", "假誘惑真哄騙"],
    aiFocus: ["是機會還是哄騙", "運勢起伏", "短期發展"],
    image: "/lenormand/dark/clover.png",
  },

  {
    id: "ship-dark",
    archetype: "ship",
    aspect: "dark",
    name: "船",
    title: "暗影之船",
    basic: "遠方、移動、變化",
    tags: ["距離", "旅行", "漂泊", "探索", "離開", "航向深淵"],
    aiFocus: ["未來方向", "關係距離", "是否即將改變"],
    image: "/lenormand/dark/ship.png",
  },

  {
    id: "house-dark",
    archetype: "house",
    aspect: "dark",
    name: "房子",
    title: "暗影宅邸",
    basic: "家庭、安全、穩定",
    tags: ["保護", "封閉", "安全感", "原生家庭", "內在世界"],
    aiFocus: ["安全感來源", "家庭影響", "穩定性", "親情困擾"],
    image: "/lenormand/dark/house.png",
  },

  {
    id: "tree-dark",
    archetype: "tree",
    aspect: "dark",
    name: "樹",
    title: "暗影之樹",
    basic: "成長、健康、累積",
    tags: ["慢性發展", "生命力", "深層問題", "穩定", "根源"],
    aiFocus: ["長期狀態", "內在能量", "健康與壓力", "固執"],
    image: "/lenormand/dark/tree.png",
  },

  {
    id: "clouds-dark",
    archetype: "clouds",
    aspect: "dark",
    name: "雲",
    title: "暗影之雲",
    basic: "混亂、不明、迷惘",
    tags: ["模糊", "困惑", "情緒遮蔽", "不安", "不確定"],
    aiFocus: ["真相是否被遮蔽", "情緒混亂", "目前盲點"],
    image: "/lenormand/dark/clouds.png",
  },

  {
    id: "snake-dark",
    archetype: "snake",
    aspect: "dark",
    name: "蛇",
    title: "暗影之蛇",
    basic: "複雜、誘惑、人際糾葛",
    tags: ["試探", "心機", "誘惑", "迂迴", "嫉妒"],
    aiFocus: ["人際問題", "隱藏情緒", "真正意圖"],
    image: "/lenormand/dark/snake.png",
  },

  {
    id: "coffin-dark",
    archetype: "coffin",
    aspect: "dark",
    name: "棺材",
    title: "暗影棺木",
    basic: "結束、停滯、轉變",
    tags: ["終結", "低潮", "釋放", "轉化", "黎明前的黑暗最黑"],
    aiFocus: ["什麼正在結束", "需要放下什麼", "轉化契機"],
    image: "/lenormand/dark/coffin.png",
  },

  {
    id: "bouquet-dark",
    archetype: "bouquet",
    aspect: "dark",
    name: "花束",
    title: "暗影花束",
    basic: "喜悅、吸引、禮物",
    tags: ["不良魅力", "被喜歡", "假性溫柔", "關注", "情感流動"],
    aiFocus: ["人際吸引力", "不當感情互動", "關係氛圍"],
    image: "/lenormand/dark/bouquet.png",
  },

  {
    id: "scythe-dark",
    archetype: "scythe",
    aspect: "dark",
    name: "鐮刀",
    title: "暗影鐮刀",
    basic: "切斷、決定、突發",
    tags: ["果斷", "切割", "危機", "突然", "疼痛", "斷捨離"],
    aiFocus: ["是否該放手", "突發事件", "關係斷裂"],
    image: "/lenormand/dark/scythe.png",
  },

  {
    id: "whip-dark",
    archetype: "whip",
    aspect: "dark",
    name: "鞭子",
    title: "暗影之鞭",
    basic: "衝突、重複、壓力",
    tags: ["爭執", "焦躁", "循環", "情緒拉扯", "對抗"],
    aiFocus: ["壓力來源", "情緒衝突", "關係拉扯"],
    image: "/lenormand/dark/whip.png",
  },

  {
    id: "birds-dark",
    archetype: "birds",
    aspect: "dark",
    name: "鳥",
    title: "暗影雙鳥",
    basic: "對話、焦慮、訊息",
    tags: ["聊天", "不安", "流言", "快速互動", "神經緊張"],
    aiFocus: ["溝通狀態", "內在焦慮", "訊息真假"],
    image: "/lenormand/dark/birds.png",
  },

  {
    id: "child-dark",
    archetype: "child",
    aspect: "dark",
    name: "孩子",
    title: "暗影之子",
    basic: "開始、純真、新階段",
    tags: ["脆弱", "單純", "新生", "不成熟", "重新開始"],
    aiFocus: ["新的可能", "是否準備好", "內在狀態"],
    image: "/lenormand/dark/child.png",
  },

  {
    id: "fox-dark",
    archetype: "fox",
    aspect: "dark",
    name: "狐狸",
    title: "暗影狐狸",
    basic: "聰明、懷疑、自保",
    tags: ["算計", "警戒", "觀察", "利益", "隱藏真心"],
    aiFocus: ["是否需要防備", "真實動機", "利益關係"],
    image: "/lenormand/dark/fox.png",
  },

  {
    id: "bear-dark",
    archetype: "bear",
    aspect: "dark",
    name: "熊",
    title: "暗影之熊",
    basic: "力量、控制、權威",
    tags: ["掌控", "保護", "壓迫", "權力", "佔有"],
    aiFocus: ["權力關係", "情緒控制", "誰掌握主導"],
    image: "/lenormand/dark/bear.png",
  },

  {
    id: "star-dark",
    archetype: "star",
    aspect: "dark",
    name: "星星",
    title: "暗影星辰",
    basic: "希望、指引、靈感",
    tags: ["夢想", "靈性", "遠景", "夜空的指引", "宇宙訊息"],
    aiFocus: ["未來方向", "內在願望", "靈性感知"],
    image: "/lenormand/dark/star.png",
  },

  {
    id: "stork-dark",
    archetype: "stork",
    aspect: "dark",
    name: "鸛",
    title: "暗影鸛鳥",
    basic: "改變、轉移、新循環",
    tags: ["遷移", "轉變", "蛻變", "流動", "重新開始"],
    aiFocus: ["變化契機", "是否適合轉換", "未來轉變"],
    image: "/lenormand/dark/stork.png",
  },

  {
    id: "dog-dark",
    archetype: "dog",
    aspect: "dark",
    name: "狗",
    title: "暗影守犬",
    basic: "朋友、忠誠、陪伴",
    tags: ["信任", "依賴", "支持", "守護", "忠誠"],
    aiFocus: ["誰值得信任", "關係忠誠度", "支持來源"],
    image: "/lenormand/dark/dog.png",
  },

  {
    id: "tower-dark",
    archetype: "tower",
    aspect: "dark",
    name: "塔",
    title: "暗影高塔",
    basic: "孤立、距離、制度",
    tags: ["疏離", "高牆", "理性", "權威", "保護自己"],
    aiFocus: ["內在距離感", "是否封閉自己", "外在壓力"],
    image: "/lenormand/dark/tower.png",
  },

  {
    id: "garden-dark",
    archetype: "garden",
    aspect: "dark",
    name: "花園",
    title: "暗影花園",
    basic: "社交、公眾、人際圈",
    tags: ["曝光", "社群", "聚會", "外在人設", "互動"],
    aiFocus: ["社交狀態", "外在人際", "群體影響"],
    image: "/lenormand/dark/garden.png",
  },

  {
    id: "mountain-dark",
    archetype: "mountain",
    aspect: "dark",
    name: "山",
    title: "暗影之山",
    basic: "阻礙、延遲、壓力",
    tags: ["卡住", "阻擋", "困難", "等待", "壓迫感"],
    aiFocus: ["目前阻礙", "是否能突破", "壓力來源"],
    image: "/lenormand/dark/mountain.png",
  },

  {
    id: "crossroads-dark",
    archetype: "crossroads",
    aspect: "dark",
    name: "十字路口",
    title: "暗影岔路",
    basic: "選擇、分岔、猶豫",
    tags: ["決定", "分歧", "迷惘", "多方向", "未知"],
    aiFocus: ["該如何選擇", "目前猶豫點", "不同未來"],
    image: "/lenormand/dark/crossroads.png",
  },

  {
    id: "mice-dark",
    archetype: "mice",
    aspect: "dark",
    name: "老鼠",
    title: "暗影鼠群",
    basic: "消耗、焦慮、流失",
    tags: ["侵蝕", "壓力", "疲憊", "失去", "細微問題"],
    aiFocus: ["正在被消耗什麼", "焦慮來源", "能量流失"],
    image: "/lenormand/dark/mice.png",
  },

  {
    id: "heart-dark",
    archetype: "heart",
    aspect: "dark",
    name: "愛心",
    title: "暗影之心",
    basic: "愛、情感、真心",
    tags: ["情感", "思念", "心動", "痛苦", "真誠", "獲得能量"],
    aiFocus: ["感情真實度", "情緒需求", "關係發展", "獲得動力"],
    image: "/lenormand/dark/heart.png",
  },

  {
    id: "ring-dark",
    archetype: "ring",
    aspect: "dark",
    name: "戒指",
    title: "暗影之戒",
    basic: "承諾、契約、循環",
    tags: ["關係", "承諾", "約定", "重複", "利益連結"],
    aiFocus: ["關係穩定度", "是否進入承諾", "契約"],
    image: "/lenormand/dark/ring.png",
  },

  {
    id: "book-dark",
    archetype: "book",
    aspect: "dark",
    name: "書",
    title: "暗影之書",
    basic: "秘密、知識、未知",
    tags: ["隱藏", "學習", "內幕", "探索", "未公開"],
    aiFocus: ["是否有隱情", "需要知道什麼", "真相層面"],
    image: "/lenormand/dark/book.png",
  },

  {
    id: "letter-dark",
    archetype: "letter",
    aspect: "dark",
    name: "信",
    title: "暗影書信",
    basic: "訊息、文字、通知",
    tags: ["聯絡", "資訊", "文件", "溝通", "壞消息"],
    aiFocus: ["是否會收到消息", "訊息內容", "溝通結果"],
    image: "/lenormand/dark/letter.png",
  },

  {
    id: "man-dark",
    archetype: "man",
    aspect: "dark",
    name: "男人",
    title: "暗影男性",
    basic: "男性能量、自我、角色",
    tags: ["陽性能量", "行動", "角色投射", "現實面", "表面"],
    aiFocus: ["關鍵人物", "主導者", "行動方"],
    image: "/lenormand/dark/man.png",
  },

  {
    id: "woman-dark",
    archetype: "woman",
    aspect: "dark",
    name: "女人",
    title: "暗影女性",
    basic: "女性能量、感受、角色",
    tags: ["陰性能量", "感受", "直覺", "情緒", "接收", "隱藏面"],
    aiFocus: ["情感流動", "關鍵人物", "內在感受", "協助"],
    image: "/lenormand/dark/woman.png",
  },

  {
    id: "lily-dark",
    archetype: "lily",
    aspect: "dark",
    name: "百合",
    title: "暗影百合",
    basic: "成熟、平靜、慾望",
    tags: ["成熟", "沉靜", "誘惑", "長久關係", "感官"],
    aiFocus: ["成熟度", "感情深度", "情慾能量"],
    image: "/lenormand/dark/lily.png",
  },

  {
    id: "sun-dark",
    archetype: "sun",
    aspect: "dark",
    name: "太陽",
    title: "暗影太陽",
    basic: "成功、力量、顯現",
    tags: ["自信", "能量", "聚焦", "熱情", "顯化"],
    aiFocus: ["是否能成功", "能量狀態", "結果走向"],
    image: "/lenormand/dark/sun.png",
  },

  {
    id: "moon-dark",
    archetype: "moon",
    aspect: "dark",
    name: "月亮",
    title: "暗影之月",
    basic: "情緒、潛意識、感受",
    tags: ["直覺", "情緒波動", "夢境", "內在世界", "敏感"],
    aiFocus: ["潛意識訊息", "情感狀態", "內在真相"],
    image: "/lenormand/dark/moon.png",
  },

  {
    id: "key-dark",
    archetype: "key",
    aspect: "dark",
    name: "鑰匙",
    title: "暗影之鑰",
    basic: "答案、開啟、命運",
    tags: ["關鍵", "突破", "命定", "解鎖", "重要性"],
    aiFocus: ["真正關鍵", "突破口", "命運轉折"],
    image: "/lenormand/dark/key.png",
  },

  {
    id: "fish-dark",
    archetype: "fish",
    aspect: "dark",
    name: "魚",
    title: "暗影之魚",
    basic: "金錢、流動、資源",
    tags: ["財務", "自由", "流動性", "價值", "交換"],
    aiFocus: ["財運狀態", "資源流向", "價值觀"],
    image: "/lenormand/dark/fish.png",
  },

  {
    id: "anchor-dark",
    archetype: "anchor",
    aspect: "dark",
    name: "錨",
    title: "暗影之錨",
    basic: "穩定、執著、停留",
    tags: ["固定", "堅持", "安全感", "停滯", "長期"],
    aiFocus: ["是否該堅持", "穩定程度", "長期發展"],
    image: "/lenormand/dark/anchor.png",
  },

  {
    id: "cross-dark",
    archetype: "cross",
    aspect: "dark",
    name: "十字架",
    title: "暗影十字",
    basic: "命運、課題、承受",
    tags: ["宿命", "壓力", "因果", "考驗", "靈魂課題", "決策"],
    aiFocus: ["人生課題", "需要學習什麼", "命運安排", "是否該決策"],
    image: "/lenormand/dark/cross.png",
  },
];